services:
   backend:
      ports:
         - 3001:3001
      build:
         context: .
         dockerfile: Dockerfile
      env_file:
         - .env
      environment:
         - NODE_ENV=production
      container_name: bdmed-pipeops
      develop:
         watch:
            - path: ./package.json
              action: rebuild
            - path: ./package-lock.json
              action: rebuild
            - path: ./
              action: sync+restart
              target: /app
